apiVersion: v2
name: pp-geoserver
type: application
version: 2.1.5
appVersion: 2.1.5
description: Chart for geoserver in openshift
dependencies:
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    condition: enabled
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
